const themes = {
  textFontSize: 16,
  colorPrimary: "#EE147D",
  colorSecondary: "blue",
  colorLight: "gainsboro",
  colorGrey: "grey",
  colorUnreadBg: "#fff0fa",
  colorDarkFont: "#1B0806",
  colorDivider: "lightgrey",
  chatInputHeight: 60,
  bubbleHeight: 10,
  bubbleMaxWidth: "85%",
  bubbleRadius: 20,
  bubbleHorizontalPadding: 10,
  bubbleTextFontSize: 16,
  bubbleLeftTextColor: "#1B0806",
  bubbleLeftBgColor: "gainsboro",
  bubbleRightBgColor: "#EE147D",
  bubbleRightTextColor: "white",
  bubbleTimeSize: 12,
  bubbleStatusSize: 14,
  bubbleStatusUnread: "lightgrey",
  bubbleStatusRead: "gold",
};

export default themes;
